services:
  migration-service:
    build: ./prisma
    command: >
      sh -c "npx prisma migrate dev --name init && npx prisma generate"
    volumes:
      - prisma_client:/usr/src/app/node_modules/@prisma/client
      - ./prisma:/usr/src/app/prisma
    depends_on:
      database:
        condition: service_healthy


  user-service:
    build: ./services/userService
    ports:
      - "3000:3000"
    command: >
      sh -c "pnpm start"
    volumes:
      - ./services/userService:/usr/src/app
      - prisma_client:/usr/src/app/node_modules/@prisma/client
    depends_on:
      database:
        condition: service_healthy

  database:
    build: ./services/database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: multi_service_db
    volumes:
      - database_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d multi_service_db"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  database_data:
  prisma_client:
