services:

  migration-service:
    build: ./prisma
    command: >
      sh -c "npx prisma migrate dev --name init && npx prisma generate"
    volumes:
      - ./prisma:/usr/src/app/prisma
      - ./.env.production:/usr/src/app/.env

  user-service:
    build: ./services/userService
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    env_file:
      - .env.production
    command: >
      sh -c "npx prisma generate && npm start"
    volumes:
      - ./services/userService:/usr/src/app
      - ./prisma:/usr/src/app/prisma
    depends_on:
      migration-service:
        condition: service_completed_successfully

  blog-service:
    build: ./services/blogService
    ports:
      - "${BLOG_SERVICE_PORT}:${BLOG_SERVICE_PORT}"
    env_file:
      - .env.production
    command: >
      sh -c "npx prisma generate && npm start"
    volumes:
      - ./services/blogService:/usr/src/app
      - ./prisma:/usr/src/app/prisma
    depends_on:
      migration-service:
        condition: service_completed_successfully

  comment-service:
    build: ./services/commentService
    ports:
      - "${COMMENT_SERVICE_PORT}:${COMMENT_SERVICE_PORT}"
    env_file:
      - .env.production
    command: >
      sh -c "npx prisma generate && npm start"
    volumes:
      - ./services/commentService:/usr/src/app
      - ./prisma:/usr/src/app/prisma
    depends_on:
      migration-service:
        condition: service_completed_successfully

