services:

  migration-service:
    build: ./prisma
    command: >
      sh -c "npx prisma migrate dev --name init && npx prisma generate"
    volumes:
      - ./prisma:/usr/src/app/prisma
      - ./.env:/usr/src/app/.env
    depends_on:
      database:
        condition: service_healthy

  user-service:
    build: ./services/userService
    ports:
      - "3000:3000"
    command: >
      sh -c "npx prisma generate && pnpm start"
    volumes:
      - ./services/userService:/usr/src/app
      - ./prisma:/usr/src/app/prisma
    depends_on:
      database:
        condition: service_healthy
      migration-service:
        condition: service_completed_successfully

  blog-service:
    build: ./services/blogService
    ports:
      - "3001:3001"
    command: >
      sh -c "npx prisma generate && pnpm start"
    volumes:
      - ./services/blogService:/usr/src/app
      - ./prisma:/usr/src/app/prisma
    depends_on:
      database:
        condition: service_healthy
      migration-service:
        condition: service_completed_successfully

  comment-service:
    build: ./services/commentService
    ports:
      - "3002:3002"
    command: >
      sh -c "npx prisma generate && pnpm start"
    volumes:
      - ./services/commentService:/usr/src/app
      - ./prisma:/usr/src/app/prisma
    depends_on:
      database:
        condition: service_healthy
      migration-service:
        condition: service_completed_successfully


  database:
    build: ./services/database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: multi_service_db
    volumes:
      - database_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d multi_service_db"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  database_data: